mongo:
  global:
    # enabled is the master enabled switch. Setting this to true or false
    # will enable or disable all the components within this chart by default.
    enabled: true
    # Used to define custom django.fullname in template.
    projectName: "mongo"
    # image sets the repo,tag and pullPolicy of the project
image:
  registry: docker.io
  repository: mongo
  tag: 4.4.14-focal
  pullPolicy: IfNotPresent

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 20
  targetCPU: 60

rbac:
  create: true
  rules: []

# Sets the username and password for mongodb. 
username: "samtheman"
password: "KSHASAHSHE322323"
