apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-practical
  name: devops-practical
spec:
  replicas: 1
  selector:
    matchLabels:
     app: devops-practical
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: devops-practical
    spec:
      containers:
      - name: devops-practical
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000
        command: ["npm", "start"]
        resources:
          requests:
            cpu: 500m
        env:
        - name: MONGODB_URL
          valueFrom:
            configMapKeyRef:
              key: MONGODB_URL
              name: env-example
