apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: devops-practical-claim1
  name: devops-practical-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
