apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: devops-practical
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: devops-practical
